// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using MetroShip.Repository.Models.Identity;
using MetroShip.Utility.Enums;
using MetroShip.Utility.Helpers;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class Notification : BaseEntity
{
    public Notification()
    {
        SentAt = CoreHelper.SystemTimeNow;
        IsRead = false;
    }

    [StringLength(50)]
    public string? ToUserId { get; set; }

    [Required]
    [StringLength(50)]
    public NotificationTypeEnum NotificationType { get; set; }

    [Required]
    [StringLength(500)]
    public string Message { get; set; }

    public bool IsRead { get; set; }

    public DateTimeOffset SentAt { get; set; }

    [ForeignKey(nameof(ToUserId))]
    [InverseProperty(nameof(UserEntity.Notifications))]
    public virtual UserEntity? User { get; set; }
}