// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class ParcelTracking : BaseEntity
{
    [Required]
    [StringLength(50)]
    public string ParcelId { get; set; }

    [Required]
    [StringLength(255)]
    public string Status { get; set; }

    [StringLength(50)]
    public string? StationId { get; set; }

    public DateTimeOffset EventTime { get; set; }

    public string? Note { get; set; }

    [ForeignKey(nameof(ParcelId))]
    [InverseProperty(nameof(Parcel.ParcelTrackings))]
    public virtual Parcel Parcel { get; set; }

    [ForeignKey(nameof(StationId))]
    [InverseProperty(nameof(Station.ParcelTrackings))]
    public virtual Station? Station { get; set; }
}