// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

[Index(nameof(RegionCode), IsUnique = true)]
public partial class Region : BaseEntity
{
    [Required]
    [StringLength(100)]
    public string RegionName { get; set; }

    [Required]
    [StringLength(50)]
    public string RegionCode { get; set; }

    [InverseProperty(nameof(MetroLine.Region))]
    public virtual ICollection<MetroLine> MetroLines { get; set; } = new List<MetroLine>();

    [InverseProperty(nameof(Station.Region))]
    public virtual ICollection<Station> Stations { get; set; } = new List<Station>();
}