// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using MetroShip.Repository.Models.Identity;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class Report : BaseEntity
{
    [Required]
    [StringLength(50)]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string ReportType { get; set; }

    public string Content { get; set; }

    public DateTimeOffset GeneratedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Reports")]
    public virtual UserEntity User { get; set; }
}