// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using MetroShip.Utility.Enums;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class ShipmentItinerary : BaseEntity
{
    public ShipmentItinerary()
    {
        // Default values can be set here if needed
        IsCompleted = false;
    }

    [Required]
    [StringLength(50)]
    public string ShipmentId { get; set; }

    // Order sequence base on customized route
    public int LegOrder { get; set; }

    [Required]
    [StringLength(50)]
    public string RouteId { get; set; }

    [StringLength(50)]
    public string? TrainId { get; set; }

    public string? TimeSlotId { get; set; }

    [Column(TypeName = "date")]
    public DateOnly? Date { get; set; }
    public bool IsCompleted { get; set; }
    public string? Message { get; set; }

    [ForeignKey(nameof(ShipmentId))]
    [InverseProperty(nameof(Shipment.ShipmentItineraries))]
    public virtual Shipment Shipment { get; set; }

    [ForeignKey(nameof(RouteId))]
    [InverseProperty(nameof(Route.ShipmentItineraries))]
    public virtual Route Route { get; set; }

    [ForeignKey(nameof(TrainId))]
    [InverseProperty(nameof(MetroTrain.ShipmentItineraries))]
    public virtual MetroTrain? Train { get; set; }

    [ForeignKey(nameof(TimeSlotId))]
    [InverseProperty(nameof(MetroTimeSlot.ShipmentItineraries))]
    public virtual MetroTimeSlot? TimeSlot { get; set; }
}