// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class ShipmentTracking : BaseEntity
{
    [Required]
    [StringLength(50)]
    public string ShipmentId { get; set; }

    [Required]
    [StringLength(255)]
    public string Status { get; set; }

    [StringLength(50)]
    public string? StationId { get; set; }

    public DateTimeOffset EventTime { get; set; }

    [StringLength(255)]
    public string Remarks { get; set; }

    [ForeignKey(nameof(ShipmentId))]
    [InverseProperty(nameof(Shipment.ShipmentTrackings))]
    public virtual Shipment Shipment { get; set; }
}