// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class ShipmentItinerary : BaseEntity
{
    [Required]
    [StringLength(50)]
    public string ShipmentId { get; set; }

    // Order sequence base on customized route
    public int LegOrder { get; set; }

    [Required]
    [StringLength(50)]
    public string RouteId { get; set; }

    public DateTimeOffset EstimatedDeparture { get; set; }

    public DateTimeOffset EstimatedArrival { get; set; }

    [ForeignKey(nameof(ShipmentId))]
    [InverseProperty(nameof(Shipment.ShipmentItineraries))]
    public virtual Shipment Shipment { get; set; }

    [ForeignKey(nameof(RouteId))]
    [InverseProperty(nameof(Route.ShipmentItineraries))]
    public virtual Route Route { get; set; }
}