// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using MetroShip.Repository.Models.Identity;
using MetroShip.Utility.Enums;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

[Index("TrackingCode", Name = "UQ__Shipment__A2A2A54B59D458B2", IsUnique = true)]
public partial class Shipment : BaseEntity
{
    public Shipment()
    {
        TrackingCode = this.GetType().Name.ToUpperInvariant();
        ShipmentStatus = ShipmentStatusEnum.WaitForApproval;
    }

    [Required]
    [StringLength(50)]
    public string TrackingCode { get; set; }

    [Required]
    [StringLength(50)]
    public string DepartureStationId { get; set; }

    [Required]
    [StringLength(50)]
    public string ArrivalStationId { get; set; }

    public ShipmentStatusEnum ShipmentStatus { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalCost { get; set; }

    public DateTimeOffset? ScheduledDate { get; set; }

    [StringLength(20)]
    public string TimeSlot { get; set; }

    public DateTimeOffset BookingAt { get; set; }

    public DateTimeOffset PickupTime { get; set; }

    [Required]
    [StringLength(50)]
    public string SenderId { get; set; }

    [Required]
    [StringLength(100)]
    public string SenderName { get; set; }

    [Required]
    [StringLength(20)]
    public string SenderPhone { get; set; }

    [StringLength(50)]
    public string? RecipientId { get; set; }

    [Required]
    [StringLength(100)]
    public string RecipientName { get; set; }

    [Required]
    [StringLength(20)]
    public string RecipientPhone { get; set; }

    [Required]
    [StringLength(20)]
    public string RecipientNationalId { get; set; }

    // Sender payment fields
    [StringLength(50)]
    public string? PaymentMethod { get; set; }

    public string? PaymentStatus { get; set; }

    [StringLength(50)]
    public string? PaymentTransactionId { get; set; }

    public DateTimeOffset? PaymentDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PaymentAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? InsuranceAmount { get; set; }

    [ForeignKey(nameof(SenderId))]
    [InverseProperty(nameof(UserEntity.Shipments))]
    public virtual UserEntity Sender { get; set; }

    [InverseProperty(nameof(Parcel.Shipment))]
    public virtual ICollection<Parcel> Parcels { get; set; } = new List<Parcel>();

    [InverseProperty(nameof(ShipmentItinerary.Shipment))]
    public virtual ICollection<ShipmentItinerary> ShipmentItineraries { get; set; } = new List<ShipmentItinerary>();

    [InverseProperty(nameof(ShipmentTracking.Shipment))]
    public virtual ICollection<ShipmentTracking> ShipmentTrackings { get; set; } = new List<ShipmentTracking>();

    [InverseProperty(nameof(SupportingTicket.Shipment))]
    public virtual ICollection<SupportingTicket> SupportingTickets { get; set; } = new List<SupportingTicket>();
}