// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

//[Index(nameof(StationCode), nameof(RegionId), IsUnique = true)]
public partial class Station : BaseEntity
{
    public Station()
    {
        IsMultiLine = false;
    }

    [StringLength(20)]
    public string? StationCode { get; set; }

    [Required]
    [StringLength(100)]
    public string StationNameVi { get; set; }

    [Required]
    [StringLength(100)]
    public string StationNameEn { get; set; }

    [StringLength(500)]
    public string Address { get; set; }

    public bool IsUnderground { get; set; }

    public bool IsActive { get; set; }

    [StringLength(50)]
    public string RegionId { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public bool IsMultiLine { get; set; }

    public string? StationCodeListJSON { get; set; }

    public List<StationCodeListItem> StationCodeList =>
        string.IsNullOrEmpty(StationCodeListJSON) ? new List<StationCodeListItem>() :
        System.Text.Json.JsonSerializer.Deserialize<List<StationCodeListItem>>(StationCodeListJSON);

    [InverseProperty(nameof(Route.FromStation))]
    public virtual ICollection<Route> RoutesFrom { get; set; } = new HashSet<Route>();

    [InverseProperty(nameof(Route.ToStation))]
    public virtual ICollection<Route> RoutesTo { get; set; } = new HashSet<Route>();

    [InverseProperty(nameof(Region.Stations))]
    public virtual Region Region { get; set; }

    [InverseProperty(nameof(StaffAssignment.Station))]
    public virtual ICollection<StaffAssignment> Staffs { get; set; } = new List<StaffAssignment>();
}

[NotMapped]
public class StationCodeListItem
{
    public string RouteId { get; set; }
    public string StationCode { get; set; }
}