// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

[Index("StationCode", Name = "UQ__Stations__A25C5AA7E98BD6EC", IsUnique = true)]
public partial class Station : BaseEntity
{
    [Required]
    [StringLength(20)]
    public string StationCode { get; set; }

    [Required]
    [StringLength(100)]
    public string StationNameVi { get; set; }

    [Required]
    [StringLength(100)]
    public string StationNameEn { get; set; }

    [StringLength(500)]
    public string Address { get; set; }

    public bool IsUnderground { get; set; }

    public bool IsActive { get; set; }

    [StringLength(50)]
    public string RegionId { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    [InverseProperty(nameof(Route.FromStation))]
    public virtual ICollection<Route> RoutesFrom { get; set; }

    [InverseProperty(nameof(Route.ToStation))]
    public virtual ICollection<Route> RoutesTo { get; set; }

    [InverseProperty(nameof(Region.Stations))]
    public virtual Region Region { get; set; }

    [InverseProperty(nameof(ParcelTracking.Station))]
    public virtual ICollection<ParcelTracking> ParcelTrackings { get; set; }
}