// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using MetroShip.Repository.Models.Identity;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class SupportingTicket : BaseEntity
{
    [Required]
    [StringLength(50)]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string ShipmentId { get; set; }

    [Required]
    [StringLength(255)]
    public string Subject { get; set; }

    public string Description { get; set; }

    public int Status { get; set; }

    public DateTimeOffset? RespondedAt { get; set; }

    [ForeignKey(nameof(ShipmentId))]
    [InverseProperty(nameof(Shipment.SupportingTickets))]
    public virtual Shipment Shipment { get; set; }

    [ForeignKey(nameof(UserId))]
    [InverseProperty(nameof(UserEntity.SupportingTickets))]
    public virtual UserEntity User { get; set; }
}