// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MetroShip.Repository.Models.Base;
using MetroShip.Repository.Models.Identity;
using MetroShip.Utility.Enums;
using Microsoft.EntityFrameworkCore;

namespace MetroShip.Repository.Models;

public partial class SupportTicket : BaseEntity
{
    public SupportTicket()
    {
        OpenedAt = DateTimeOffset.UtcNow;
        Status = SupportTicketStatusEnum.Opened;
    }

    [Required]
    [StringLength(50)]
    public string OpenById { get; set; }

    [StringLength(50)]
    public string? ResolvedById { get; set; }

    [Required]
    [StringLength(50)]
    public string ShipmentId { get; set; }

    [Required]
    [StringLength(255)]
    public string Subject { get; set; }

    public string Description { get; set; }

    public string? ResolvedContent { get; set; }

    public SupportTypeEnum SupportType { get; set; }

    public SupportTicketStatusEnum Status { get; set; }

    public DateTimeOffset OpenedAt { get; set; }

    public DateTimeOffset? ResolvedAt { get; set; }
    public DateTimeOffset? ClosedAt { get; set; }
    public string? ClosedBy { get; set; }

    [ForeignKey(nameof(ShipmentId))]
    [InverseProperty(nameof(Shipment.SupportTickets))]
    public virtual Shipment Shipment { get; set; }

    [ForeignKey(nameof(OpenById))]
    [InverseProperty(nameof(UserEntity.OpenedSupportTickets))]
    public virtual UserEntity OpenBy { get; set; }

    [ForeignKey(nameof(ResolvedById))]
    [InverseProperty(nameof(UserEntity.ResolvedSupportTickets))]
    public virtual UserEntity? ResolvedBy { get; set; }
}